[profile.default]
test            = "tests"                  # The test directory
libs            = ["lib", "node_modules"]  # A list of library directories 
optimizer       = false                    # Enable or disable the solc optimizer
optimizer_runs  = 200                      # The number of optimizer runs
verbosity       = 3                        # The verbosity of tests
solc_version    = "0.8.17"                 # The solc version to use